---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library('ggplot2')
library('forecast')
library('tseries')
library('chron')
library('sas7bdat')
library('lubridate')
```


```{r}
pred_table = setNames(data.frame(matrix(ncol =6, nrow = 0)), c("Pred Nr","Pred","Obs", "Mape","Mae","Rmse"))
data = read.csv("freeway_data/freeway_data2.csv")
colnames(data) = c("Date","Count")
data$Time <-format(as.POSIXct(data$Date) ,format = "%H:%M:%S")
data$Date <- as.Date(data$Date)

df <- data.frame(Date = data$Date,
                 Time = data$Time,
                 x = data$Count)

#train <- subset(data, Date < "2002-03-01" )
#test <- subset(data, Date >= "2002-03-01" )

cutoff = round(0.8*nrow(data))

train = data[1:cutoff,]

test = data[-(1:cutoff),]

```

```{r}
#for (i in 1:1){ #change for 96

#data$Date = as.character(data$Date)
start_date = decimal_date(as.Date(train$Date[1]))
#diff = as.numeric(as.Date("2002-08-01")-as.Date("2002-01-01"))
myts_train <- ts(train$Count, start = start_date,frequency = 96)
#myts_test <- ts(test$Count, start = decimal_date(as.Date("2002-03-01")), frequency = 96)
start_time <- Sys.time()
model <- Arima(myts_train, order=c(3,0,2), seasonal = list(order = c(0, 1, 0), period = 96))
#model = auto.arima(myts_train, seasonal = TRUE)
end_time <- Sys.time()
elapsed = end_time-start_time


obs_data = test[1,]
obs = obs_data$Count

pred = predict(model,n.ahead = 1)
pred_values = pred$pred
pred_values = as.numeric(pred_values)

error <- pred_values-obs

mapeError = mape(error,obs)
maeError = mae(error)
rmsError = rmse(error)

ar_order = model$arma[1]
ma_order = model$arma[2]

s_ar_order = model$arma[3]
s_ma_order = model$arma[4]

period_of_data = model$arma[5] # 1 for is non-seasonal data

diff_order = model$arma[6]
s_diff_order =  model$arma[7]

ns = paste ("(",ar_order,",",diff_order,",",ma_order,")", sep = "", collapse = NULL)
s = paste ("(",s_ar_order,",",s_diff_order,",",s_ma_order,")", sep = "", collapse = NULL)
model_coef = paste(ns,s,sep="x")

pred_table[nrow(pred_table) + 1,] =list(1,pred_values,obs,mapeError,maeError,rmsError)
save(pred_table,file="/home/vasco/pred_table.RData")

train = train[-1,]
new_obs = test[1,]
test = test[-1,]

train[nrow(train) + 1,] = new_obs

#}



#myts_test <- ts(test$Count, start=1, end=8832, frequency=96)

```